<?php

namespace Database\Seeders;

use App\Models\Umkm;
use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Str;

class UmkmSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            // Fashion
            [
                'name' => 'Batik Nusantara',
                'slug' => Str::slug('Batik Nusantara'),
                'category_id' => 1,
                'description' => 'Menjual batik tradisional khas Yogyakarta dengan motif eksklusif dan kualitas premium.',
                'location' => 'Yogyakarta',
                'address' => 'Jl. Malioboro No.10, Yogyakarta',
                'phone' => '081234567890',
                'email' => 'info@batiknusantara.com',
                'website' => 'https://batiknusantara.com',
                'instagram' => 'batiknusantara',
                'tiktok' => null,
                'facebook' => 'batiknusantara',
                'registered_at' => Carbon::parse('2023-01-15'),
                'open_hour' => '09:00',
                'close_hour' => '18:00',
                'total_products' => 25,
                'logo' => null,
                'map_embed_url' => null,
            ],
            [
                'name' => 'Hijab Modernku',
                'slug' => Str::slug('Hijab Modernku'),
                'category_id' => 1,
                'description' => 'Toko hijab kekinian dengan berbagai model instan dan pashmina untuk remaja.',
                'location' => 'Bandung',
                'address' => 'Jl. Dago Atas No.7, Bandung',
                'phone' => '081298765432',
                'email' => null,
                'website' => null,
                'instagram' => 'hijabmodernku',
                'tiktok' => 'hijabmodernku',
                'facebook' => null,
                'registered_at' => Carbon::parse('2023-06-20'),
                'open_hour' => '10:00',
                'close_hour' => '20:00',
                'total_products' => 40,
                'logo' => null,
                'map_embed_url' => null,
            ],

            // Kerajinan Kriya
            [
                'name' => 'Kriya Kayu Lestari',
                'slug' => Str::slug('Kriya Kayu Lestari'),
                'category_id' => 2,
                'description' => 'Kerajinan tangan dari kayu jati dan mahoni, cocok untuk dekorasi rumah dan kantor.',
                'location' => 'Jepara',
                'address' => 'Jl. Ukir No.21, Jepara',
                'phone' => '082123456789',
                'email' => 'info@kriyakayu.id',
                'website' => null,
                'instagram' => 'kriyakayulestari',
                'tiktok' => null,
                'facebook' => null,
                'registered_at' => Carbon::parse('2022-11-01'),
                'open_hour' => '08:00',
                'close_hour' => '17:00',
                'total_products' => 18,
                'logo' => null,
                'map_embed_url' => null,
            ],
            [
                'name' => 'Anyaman Bambu Asri',
                'slug' => Str::slug('Anyaman Bambu Asri'),
                'category_id' => 2,
                'description' => 'Produk anyaman bambu seperti keranjang, tempat tisu, dan dekorasi rumah ramah lingkungan.',
                'location' => 'Tasikmalaya',
                'address' => 'Desa Rajapolah No.5, Tasikmalaya',
                'phone' => '082198123456',
                'email' => null,
                'website' => null,
                'instagram' => null,
                'tiktok' => 'anyamanasri',
                'facebook' => 'Anyaman Asri',
                'registered_at' => Carbon::parse('2023-04-10'),
                'open_hour' => '09:00',
                'close_hour' => '16:00',
                'total_products' => 30,
                'logo' => null,
                'map_embed_url' => null,
            ],

            // Jasa
            [
                'name' => 'Service Laptop Jogja',
                'slug' => Str::slug('Service Laptop Jogja'),
                'category_id' => 3,
                'description' => 'Layanan servis laptop, instalasi software, dan upgrade hardware profesional.',
                'location' => 'Yogyakarta',
                'address' => 'Jl. Kaliurang KM 7 No.12, Sleman',
                'phone' => '085232123123',
                'email' => 'servisjogja@gmail.com',
                'website' => null,
                'instagram' => 'servicelaptopjogja',
                'tiktok' => null,
                'facebook' => 'servisjogja',
                'registered_at' => Carbon::parse('2024-02-01'),
                'open_hour' => '08:30',
                'close_hour' => '18:00',
                'total_products' => 0,
                'logo' => null,
                'map_embed_url' => null,
            ],
            [
                'name' => 'Laundry Express Cuci Bersih',
                'slug' => Str::slug('Laundry Express Cuci Bersih'),
                'category_id' => 3,
                'description' => 'Layanan laundry kilat dengan antar jemput gratis di area Jabodetabek.',
                'location' => 'Jakarta',
                'address' => 'Jl. Kemang Raya No.4, Jakarta Selatan',
                'phone' => '085678910111',
                'email' => 'cs@cucibersih.id',
                'website' => 'https://cucibersih.id',
                'instagram' => 'cucibersih',
                'tiktok' => null,
                'facebook' => null,
                'registered_at' => Carbon::parse('2023-09-10'),
                'open_hour' => '07:00',
                'close_hour' => '21:00',
                'total_products' => 0,
                'logo' => null,
                'map_embed_url' => null,
            ],

            // Kesehatan & Kecantikan
            [
                'name' => 'Herbal Sehat Alami',
                'slug' => Str::slug('Herbal Sehat Alami'),
                'category_id' => 4,
                'description' => 'Menyediakan produk herbal alami seperti madu, jamu, dan suplemen tradisional.',
                'location' => 'Bogor',
                'address' => 'Jl. Cibinong Raya No.9, Bogor',
                'phone' => '087812345678',
                'email' => 'herbalalami@gmail.com',
                'website' => null,
                'instagram' => 'herbalsehatalami',
                'tiktok' => 'herbalsehat',
                'facebook' => null,
                'registered_at' => Carbon::parse('2024-03-05'),
                'open_hour' => '09:00',
                'close_hour' => '17:00',
                'total_products' => 12,
                'logo' => null,
                'map_embed_url' => null,
            ],
            [
                'name' => 'Beauty Glow Skincare',
                'slug' => Str::slug('Beauty Glow Skincare'),
                'category_id' => 4,
                'description' => 'Skincare lokal dengan kandungan natural, cocok untuk semua jenis kulit.',
                'location' => 'Surabaya',
                'address' => 'Jl. Tunjungan No.33, Surabaya',
                'phone' => '085811223344',
                'email' => 'glowskincare@beauty.id',
                'website' => 'https://beautyglowskin.id',
                'instagram' => 'beautyglowskincare',
                'tiktok' => 'glowskincare',
                'facebook' => 'Beauty Glow',
                'registered_at' => Carbon::parse('2023-08-25'),
                'open_hour' => '10:00',
                'close_hour' => '18:00',
                'total_products' => 15,
                'logo' => null,
                'map_embed_url' => null,
            ],

            // Handphone & Aksesoris
            [
                'name' => 'Gadget Mart',
                'slug' => Str::slug('Gadget Mart'),
                'category_id' => 5,
                'description' => 'Toko handphone dan aksesoris original, lengkap dengan layanan garansi resmi.',
                'location' => 'Semarang',
                'address' => 'Jl. Pandanaran No.5, Semarang',
                'phone' => '081234000123',
                'email' => 'cs@gadgetmart.co.id',
                'website' => 'https://gadgetmart.co.id',
                'instagram' => 'gadgetmart',
                'tiktok' => null,
                'facebook' => null,
                'registered_at' => Carbon::parse('2022-12-10'),
                'open_hour' => '09:00',
                'close_hour' => '21:00',
                'total_products' => 60,
                'logo' => null,
                'map_embed_url' => null,
            ],
            [
                'name' => 'Aksesoris HP Murah',
                'slug' => Str::slug('Aksesoris HP Murah'),
                'category_id' => 5,
                'description' => 'Menjual casing, tempered glass, dan kabel charger dengan harga terjangkau.',
                'location' => 'Depok',
                'address' => 'Jl. Margonda Raya No.100, Depok',
                'phone' => '081299988877',
                'email' => null,
                'website' => null,
                'instagram' => null,
                'tiktok' => 'akshpmurah',
                'facebook' => 'akshpmurah',
                'registered_at' => Carbon::parse('2023-05-15'),
                'open_hour' => '08:00',
                'close_hour' => '19:00',
                'total_products' => 80,
                'logo' => null,
                'map_embed_url' => null,
            ],
        ];

        foreach ($data as $item) {
            Umkm::create($item);
        }
    }
}
